
name: Create tagged release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    #

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    steps:
      -
        name: Action Checkout
        uses: actions/checkout@v3
      -
        name: Setup Tinygo
        uses: acifani/setup-tinygo@v1
        with:
          tinygo-version: '0.28.1'
      -
        name: Parse build tag
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      -
        name: Build wasm
        run: |
          mkdir output
          /usr/bin/env bash ./cmds/mcla_wasm/build.sh -o ./output/mcla.wasm -ldflags="-X 'main.version=${RELEASE_VERSION}'"
          cp ./cmds/mcla_wasm/wasm_exec.js ./output/wasm_exec.js
      -
        name: Upload build output to artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-wasm-output
          path: output/mcla.wasm
      -
        name: Upload tinygo wasm_exec to artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-wasm-exec-js
          path: output/wasm_exec.js

  publish-release:
    runs-on: ubuntu-latest
    needs:
      - build-wasm
    steps:
      -
        name: Download build-wasm output from artifact
        uses: actions/download-artifact@v2
        with:
          name: build-wasm-output
          path: output
      -
        name: Download tinygo wasm_exec from artifact
        uses: actions/download-artifact@v2
        with:
          name: build-wasm-exec-js
          path: output
      -
        name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false
      -
        name: Upload Release Assets
        uses: zyxkad/upload-release-asset-dir@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_dir: ./output

  deploy-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs:
      - build-wasm
    steps:
      -
        name: Download build-wasm output from artifact
        uses: actions/download-artifact@v2
        with:
          name: build-wasm-output
          path: .
      -
        name: Download tinygo wasm_exec from artifact
        uses: actions/download-artifact@v2
        with:
          name: build-wasm-exec-js
          path: .
      -
        name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload contents artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .
      -
        name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

