
name: Create tagged release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    steps:
      -
        name: Action Checkout
        uses: actions/checkout@v3
      -
        name: Setup Tinygo
        uses: acifani/setup-tinygo@v1
        with:
          tinygo-version: '0.28.1'
      -
        name: Build wasm
        run: |
          mkdir output
          /usr/bin/env bash ./cmds/mcla_wasm/build.sh -o ./output/mcla.wasm -ldflags="-X 'main.version=${GITHUB_REF#refs/*/}'"
          cp ./cmds/mcla_wasm/wasm_exec.js ./output/wasm_exec.js
      -
        name: Upload build output to artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-wasm-output
          path: output/mcla.wasm
      -
        name: Upload tinygo wasm_exec to artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-wasm-exec-js
          path: output/wasm_exec.js

  publish-release:
    runs-on: ubuntu-latest
    needs:
      - build-wasm
    steps:
      -
        name: Download build-wasm output from artifact
        uses: actions/download-artifact@v2
        with:
          name: build-wasm-output
          path: output
      -
        name: Download tinygo wasm_exec from artifact
        uses: actions/download-artifact@v2
        with:
          name: build-wasm-exec-js
          path: output
      -
        name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false
      -
        name: Upload Release Assets
        uses: zyxkad/upload-release-asset-dir@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_dir: ./output

  publish-pages:
    runs-on: ubuntu-latest
    needs:
      - build-wasm
    steps:
      -
        name: Action Checkout
        uses: actions/checkout@v3
        with:
          ref: 'pages'
      -
        name: Download build-wasm output from artifact
        uses: actions/download-artifact@v2
        with:
          name: build-wasm-output
          path: .
      -
        name: Download tinygo wasm_exec from artifact
        uses: actions/download-artifact@v2
        with:
          name: build-wasm-exec-js
          path: .
      -
        name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "published"
          git push
