
name: Create tagged release

on:
  push:
    tags:
      - 'v*'

jobs:
  release-docker-images:
    runs-on: ubuntu-latest
    steps:
      -
        name: Action Checkout
        uses: actions/checkout@v3
      -
        name: Setup Tinygo
        uses: acifani/setup-tinygo@v1
        with:
          tinygo-version: '0.28.1'
      -
        name: Parse build tag
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      -
        name: Build wasm
        run: |
          mkdir output
          /usr/bin/env bash ./cmds/mcla_wasm/build.sh -o ./output/mcla.wasm -ldflags="-X 'main.version=${RELEASE_VERSION}'"
          cp ./cmds/mcla_wasm/wasm_exec.js ./output/wasm_exec.js
      -
        name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false
      -
        name: Upload Release Assets
        uses: zyxkad/upload-release-asset-dir@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_dir: ./output
